spring:
#  mvc:
#    static-path-pattern:/dist/**
  datasource:
    username: root
    password: "6150"
    url: jdbc:mysql://localhost:3306/videowatcher?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

# 用自己的邮箱设置！！！
  mail:
    host: smtp.126.com #发送邮件服务器
    username: xqsx48pky@126.com #发送邮件的邮箱地址
    password: YTHJJSMZFRQVKRLE #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: xqsx48pky@126.com # 发送邮件的地址，和上面username一致
    properties:
      mail:
        smtp:
          port: 994 #465或者994
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    default-encoding: utf-8

  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    suffix: .html

  messages:
    basename: i18n.login

server:
  port: 8082

mybatis:
  type-aliases-package: com.pky.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

#autoconfigure:
#  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

